#!/bin/bash
#PBS -l nodes=1:ppn=4,walltime=0:20:00
#PBS -N app-compute-temporal-snr
#PBS -l vmem=16gb
#PBS -V

echo "computing snr"
time singularity exec -e docker://brainlife/fsl:5.0.9 ./compute-snr.sh
